<a href="https://colab.research.google.com/github/Matinnorouzi2023/deeplearning-tensorflow-notebooks-master/blob/main/01_PyTorch_Basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# Imports

In [2]:
import torch
import numpy as np

In [3]:
torch.__version__

'2.11.0+cu128'

# **Tensor Initialisation**

## From data

* `torch.tensor()`

In [188]:
data = [[1., 2.], [3., 4.]]
type(data)

list

In [189]:
data_tensor = torch.tensor(data, dtype=torch.int32)
data_tensor
data_tensor.dtype

torch.int32

## From NumPy arrays

* `torch.from_numpy()`
* `torch.as_tensor()`


In [6]:
data_array = np.array(data)
type(data_array)

numpy.ndarray

In [7]:
# torch.from_numpy()

In [8]:
a = torch.from_numpy(data_array)
a

tensor([[1., 2.],
        [3., 4.]], dtype=torch.float64)

In [9]:
# torch.as_tensor()

In [10]:
b = torch.as_tensor(data_array)
b

tensor([[1., 2.],
        [3., 4.]], dtype=torch.float64)

## With random or constant values

* `torch.zeros()`
* `torch.ones()`
* `torch.eye()`
* `torch.rand()`
* `torch.randn()`
* `torch.randint()`
* `torch.rand_like()`
* `torch.randn_like()`
* `torch.randint_like()`
* `torch.empty()`
* `torch.diag()`

In [11]:
# torch.zeros()

In [12]:
zeros_tensor = torch.zeros(3, 4)
zeros_tensor.dtype


torch.float32

In [13]:
# torch.ones()

In [14]:
ones_tensor = torch.ones(3, 4)
ones_tensor

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [15]:
# torch.eye()

In [16]:
eye_tensor = torch.eye(4, 4)
eye_tensor

tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])

In [17]:
# torch.rand()

In [18]:
rand_tensor = torch.rand(3, 3)
rand_tensor

tensor([[0.6521, 0.1263, 0.8551],
        [0.5386, 0.2608, 0.7476],
        [0.7448, 0.4416, 0.5433]])

In [19]:
# torch.randn()

In [20]:
randn_tensor = torch.randn(4, 4)
randn_tensor

tensor([[ 0.3095, -1.2998, -1.1095, -1.2178],
        [-0.7639, -0.5476,  2.3668,  0.9697],
        [ 0.6476, -0.3863, -0.1119,  0.9264],
        [ 0.4828,  0.2266,  0.7441,  0.1529]])

In [21]:
# torch.randint()

In [22]:
randint_tensor = torch.randint(1, 10, (4, 4))
randint_tensor

tensor([[4, 6, 5, 5],
        [5, 6, 2, 8],
        [7, 9, 8, 5],
        [8, 7, 3, 4]])

In [23]:
# torch.rand_like()

In [24]:
base = [[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]

In [25]:
base_tensor = torch.tensor(base, dtype=torch.float32)
base_tensor

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])

In [26]:
randlike_tensor = torch.rand_like(base_tensor)
randlike_tensor

tensor([[0.3814, 0.4981, 0.5386],
        [0.2173, 0.3667, 0.9316],
        [0.9878, 0.0680, 0.4424]])

In [27]:
# torch.randn_like()

In [28]:
randn_like_tensor = torch.randn_like(base_tensor)
randn_like_tensor

tensor([[-1.1305, -0.3698, -0.0744],
        [-0.7226, -0.5915,  0.7901],
        [ 2.0697, -2.3406, -0.7627]])

In [29]:
# torch.randint_like()

In [30]:
randint_like_tensor = torch.randint_like(base_tensor, 1, 10)
randint_like_tensor

tensor([[9., 9., 9.],
        [4., 3., 2.],
        [5., 5., 6.]])

In [31]:
# torch.zeros_like()


In [32]:
zeroslike_tensor = torch.zeros_like(base_tensor)

In [33]:
# torch.ones_like()

In [34]:
oneslike_tensor = torch.ones_like(base_tensor)
oneslike_tensor

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [35]:
# torch.empty()

In [ ]:
empty_tensor = torch.empty(4, 4)
empty_tensor

tensor([[0.0000e+00, 0.0000e+00, 1.8535e-17, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00]])

In [ ]:
# torch.diag()
# torch.diag()

In [38]:
a = torch.randn(3)

In [39]:
a

tensor([-0.1481, -0.4452,  0.9153])

In [40]:
diag_tensor = torch.diag(a)
diag_tensor

tensor([[-0.1481,  0.0000,  0.0000],
        [ 0.0000, -0.4452,  0.0000],
        [ 0.0000,  0.0000,  0.9153]])

## Creating tensors from ranges

* `torch.arange()`
* `torch.linspace()`





In [41]:
# torch.arange(start, end, steps)

In [42]:
a = torch.arange(6)
a

tensor([0, 1, 2, 3, 4, 5])

In [43]:
b = torch.arange(1, 5)
b

tensor([1, 2, 3, 4])

In [44]:
c = torch.arange(1, 3, 0.5)
c

tensor([1.0000, 1.5000, 2.0000, 2.5000])

In [45]:
# torch.linspace(start, end, steps)

In [46]:
e = torch.linspace(3, 10, steps=5)
e

tensor([ 3.0000,  4.7500,  6.5000,  8.2500, 10.0000])

## Attributes

* `tensor.shape`>>(`tensor.size()`)
* `tensor.dtype`
* `tensor.device`

In [47]:
my_tensor = torch.rand(3, 4)

In [48]:
# tensor.shape

In [49]:
print(f'Tensor shape is: {my_tensor.shape}')
print(f'Tensor size is: {my_tensor.size()}')

Tensor shape is: torch.Size([3, 4])
Tensor size is: torch.Size([3, 4])


In [50]:
# tensor.dtype

In [51]:
print(f'Tensor data type: {my_tensor.dtype}')

Tensor data type: torch.float32


In [52]:
# tensor.device

In [53]:
print(f'Tensor device: {my_tensor.device}')

Tensor device: cpu


In [54]:
device = 'cuda' if torch.cuda.is_available() else 'cpu'

In [55]:
device

'cuda'

In [56]:
my_tensor.to(device)

tensor([[0.7715, 0.3637, 0.6947, 0.6091],
        [0.8165, 0.4233, 0.1088, 0.6130],
        [0.2038, 0.3487, 0.9311, 0.1103]], device='cuda:0')

In [57]:
!nvidia-smi

Sat Jun  6 19:16:00 2026       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 580.82.07              Driver Version: 580.82.07      CUDA Version: 13.0     |
+-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   37C    P0             27W /   70W |     123MiB /  15360MiB |      1%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

# **Operations**

## Indexing and Slicing

In [126]:
tensor = torch.randint(1, 10, (4, 4))

In [127]:
tensor

tensor([[5, 7, 2, 9],
        [5, 2, 8, 2],
        [9, 6, 5, 7],
        [2, 9, 6, 4]])

In [128]:
print(f'First row: ', tensor[0])

First row:  tensor([5, 7, 2, 9])


In [129]:
print(f'First Column: ', tensor[:, 0])

First Column:  tensor([5, 5, 9, 2])


In [130]:
tensor[-1:, -1:]

tensor([[4]])

In [131]:
tensor[:, 1] = 5

In [132]:
tensor

tensor([[5, 5, 2, 9],
        [5, 5, 8, 2],
        [9, 5, 5, 7],
        [2, 5, 6, 4]])

## Joining tensors

* `torch.cat()`
* `torch.stack()`

In [133]:
a = torch.randint(1, 5, (4, 4))
b = torch.randint(5, 10, (4, 4))

In [134]:
# torch.cat()

In [135]:
cat_tensor = torch.cat((a, b), dim=0)

In [136]:
cat_tensor

tensor([[2, 2, 2, 3],
        [1, 2, 3, 3],
        [1, 1, 3, 3],
        [1, 3, 2, 1],
        [6, 6, 6, 7],
        [7, 9, 8, 6],
        [9, 5, 8, 7],
        [9, 6, 5, 8]])

In [137]:
# torch.stack()

In [138]:
stack_tensor = torch.stack((a, b), dim=0)

In [139]:
stack_tensor

tensor([[[2, 2, 2, 3],
         [1, 2, 3, 3],
         [1, 1, 3, 3],
         [1, 3, 2, 1]],

        [[6, 6, 6, 7],
         [7, 9, 8, 6],
         [9, 5, 8, 7],
         [9, 6, 5, 8]]])

## Reshaping a tensor
* `torch.view()`
* `torch.reshape()`
* `torch.view_as()`

In [140]:
x = torch.rand(16)

In [141]:
# torch.view()

In [142]:
y = x.view(4, 4)
y

tensor([[0.2977, 0.3807, 0.1314, 0.4766],
        [0.8553, 0.7723, 0.3888, 0.9363],
        [0.3666, 0.5533, 0.7696, 0.3469],
        [0.8814, 0.9387, 0.5617, 0.5320]])

In [143]:
# torch.reshape()

In [144]:
a = torch.arange(4)

In [145]:
a

tensor([0, 1, 2, 3])

In [146]:
torch.reshape(a, (2, 2))

tensor([[0, 1],
        [2, 3]])

In [147]:
# torch.view_as()

## Arithmetic Operations


In [148]:
tensor_a = torch.tensor([[1, 2], [1, 3]])
tensor_b = torch.tensor([[2, 3], [0, 4]])

In [149]:
# Addition

In [150]:
print(tensor_a + tensor_b)

tensor([[3, 5],
        [1, 7]])


In [151]:
# Subtraction

In [152]:
print(tensor_a - tensor_b)

tensor([[-1, -1],
        [ 1, -1]])


In [153]:
# Multiplication

In [154]:
print(tensor_a * tensor_b)

tensor([[ 2,  6],
        [ 0, 12]])


In [155]:
# Division

In [156]:
print(tensor_a / tensor_b)

tensor([[0.5000, 0.6667],
        [   inf, 0.7500]])


In [157]:
# Exponent

In [158]:
print(tensor_a ** tensor_b)

tensor([[ 1,  8],
        [ 1, 81]])


In [159]:
# Matrix Multiplication

In [160]:
mytensor = torch.randint(1, 5, (4, 4))

In [161]:
matrix_mul = mytensor @ mytensor.T

In [162]:
print(matrix_mul)

tensor([[10, 11, 22, 15],
        [11, 22, 27, 14],
        [22, 27, 50, 33],
        [15, 14, 33, 25]])


In [163]:
matrix_mul_new = mytensor.matmul(mytensor.T)
matrix_mul_new

tensor([[10, 11, 22, 15],
        [11, 22, 27, 14],
        [22, 27, 50, 33],
        [15, 14, 33, 25]])

## Single-element tensors

In [164]:
# torch.item()

In [165]:
mytensor

tensor([[1, 2, 2, 1],
        [1, 2, 1, 4],
        [3, 4, 4, 3],
        [2, 2, 4, 1]])

In [166]:
agg = mytensor.sum()
agg

tensor(37)

In [167]:
agg_item = agg.item()
print(agg_item, type(agg_item))

37 <class 'int'>


## In-place Operations






In [168]:
x = torch.rand(1)
y = torch.rand(1)

In [169]:
x, y

(tensor([0.2151]), tensor([0.6582]))

In [170]:
# Noraml Addition

In [171]:
x + y

tensor([0.8734])

In [172]:
x

tensor([0.2151])

In [173]:
# In-place Addition

In [174]:
x.add_(y)

tensor([0.8734])

In [175]:
x

tensor([0.8734])

## Other Operations



* Common Functions
* Trigonometric Functions
* Bitwise Operations
* Comparison Operations
* Reduction Operations
* Linear Algebra Operations


|| Some Useful Operations||
|:--- | :---: |  ---:  |
|`torch.max()`|`torch.norm()`|`torch.ndimension`|
|`torch.min()`|`torch.mean()`|`torch.remainder`|
|`torch.sum()`|`torch.eq()`|`torch.where()`|
|`torch.abs()`|`torch.clamp()`|`torch.numel()`|
|`torch.argmax()`|`torch.sort()`|`torch.clone()`|
|`torch.argmin()`|`torch.any()`|`torch.squeeze()`|
|`torch.sqrt()`|`torch.all()`|`torch.unsqueeze()`|
|`torch.exp()`|`torch.unique()`|`torch.t()`|


In [176]:
a = torch.ones(2, 2)

In [177]:
b = a

a[0][1] = 777

print(b)

tensor([[  1., 777.],
        [  1.,   1.]])


In [178]:
a = torch.ones(2, 2)
b = a.clone()

In [179]:
assert b is not a
print(torch.eq(a, b))

tensor([[True, True],
        [True, True]])


In [180]:
a[0][1] = 777
print(b)

tensor([[1., 1.],
        [1., 1.]])


In [181]:
a = torch.rand(2, 2, requires_grad=True)
print(a)

tensor([[0.1316, 0.5187],
        [0.5107, 0.6183]], requires_grad=True)


In [182]:
b = a.clone()
print(b)

tensor([[0.1316, 0.5187],
        [0.5107, 0.6183]], grad_fn=<CloneBackward0>)


In [183]:
c = a.detach().clone()
print(c)

tensor([[0.1316, 0.5187],
        [0.5107, 0.6183]])


In [184]:
# 3 x 256 x 256 --> Image size

# N x 3 x 256 x 256 --> N is the Batch size

a = torch.rand(3, 256, 256)
b = a.unsqueeze(0)

print(a.shape)
print(b.shape)

torch.Size([3, 256, 256])
torch.Size([1, 3, 256, 256])


In [185]:
c = torch.rand(1, 1, 1, 1, 1, 1)
print(c)

tensor([[[[[[0.5068]]]]]])


In [186]:
a = torch.rand(1, 20)
print(a.shape)
print(a)

torch.Size([1, 20])
tensor([[0.1004, 0.4544, 0.2771, 0.1122, 0.7006, 0.3815, 0.3305, 0.8174, 0.9771,
         0.7356, 0.7086, 0.3734, 0.4791, 0.0882, 0.0460, 0.8935, 0.8845, 0.3156,
         0.0494, 0.5013]])


In [187]:
b = a.squeeze(0)
print(b.shape)
print(b)

torch.Size([20])
tensor([0.1004, 0.4544, 0.2771, 0.1122, 0.7006, 0.3815, 0.3305, 0.8174, 0.9771,
        0.7356, 0.7086, 0.3734, 0.4791, 0.0882, 0.0460, 0.8935, 0.8845, 0.3156,
        0.0494, 0.5013])


# Interopreability

## NumPy array to tensor

In [120]:
numpy_array = np.ones((2, 3))

In [121]:
print(numpy_array)

[[1. 1. 1.]
 [1. 1. 1.]]


In [122]:
pytorch_tensor = torch.from_numpy(numpy_array)
print(pytorch_tensor)

tensor([[1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)


In [123]:
print(type(numpy_array), numpy_array.dtype)
print(type(pytorch_tensor), pytorch_tensor.dtype)

<class 'numpy.ndarray'> float64
<class 'torch.Tensor'> torch.float64


In [124]:
pytorch_rand = torch.rand(2, 3)
print(pytorch_rand)

tensor([[0.1985, 0.9822, 0.1997],
        [0.5165, 0.3436, 0.0299]])


In [125]:
numpy_rand = pytorch_rand.numpy()
print(numpy_rand)

[[0.19849122 0.9822327  0.19965583]
 [0.516466   0.34361207 0.02986366]]
